- name: Deploy qBittorrent and Nextcloud using Docker Compose
  hosts: NexCloud
  become: true
  tasks:
    - name: Clone GitHub repository containing Docker Compose configuration
      git:
        repo: https://github.com/SKAYY404/nexcloud-docker-disk-qbitorent.git
        dest: /home/zora/nexcloud-docker-disk-qbitorent
        version: main

    - name: Ensure the directory exists
      file:
        path: /home/zora/nexcloud-docker-disk-qbitorent
        state: directory
        mode: '0755'

    # ДОБАВЬТЕ ЭТУ ЗАДАЧУ:
    - name: Replace password in docker-compose.yml
      replace:
        path: /home/zora/nexcloud-docker-disk-qbitorent/docker-compose.yml
        regexp: 'NEXTCLOUD_ADMIN_PASSWORD=admin123'
        replace: 'NEXTCLOUD_ADMIN_PASSWORD={{ nextcloud_admin_password }}'

    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present
      when: ansible_os_family == "Debian"

    - name: Run Docker Compose to start the services
      command: docker-compose up -d
      args:
        chdir: /home/zora/nexcloud-docker-disk-qbitorent
